### ISSUE TITLE
Github action worker running out of space

### ISSUE THREAD

**Issue by arm61** [rodluger/showyourwork#67] opened 2021-12-02 10:11 UTC
My GitHub action fails when constructing the ArXiv tarball with the following error 
```
System.IO.IOException: No space left on device
``` 
This *appears* to be after all of the data downloaded from Zenodo is removed, but I am not exactly clear. 

I recognise this probably isn't a `showyourwork` problem (my untarred Zenodo data is > 18 Gb) but I am confused cause the Zenodo data seems to be removed.

Any thoughts?

**Comment by rodluger** [comment] 2021-12-02 14:32
I think I know what the issue is. `showyourwork` automatically ignores datasets when uploading to Zenodo, but for tarballs it may only be ignoring the tarball itself (and still trying to tar up the contents of the tarball). I'll look into this today. In the meantime, you could set the `arxiv-tarball` option to `false` in `.github/workflows/showyourwork.yml`:

```
      - name: Build the article PDF
        id: build
        uses: ./showyourwork/showyourwork-action
        with:
          arxiv-tarball: false
        ...
```

which will skip the tarball generation step.

**Comment by arm61** [comment] 2021-12-02 15:02
Awesome, this works for now cheers!

**Comment by rodluger** [comment] 2021-12-02 15:32
Cool. This is now fixed on the `dev` branch and will be released in the next patch (a day or two I think).

**Comment by arm61** [comment] 2021-12-02 15:57
Fab, let's keep this open until the new patch it out 🙂.

**Closed** 2021-12-07 20:43 UTC
Labels: bug, v0.2.0

**Comment by arm61** [comment] 2021-12-08 14:11
the `0.2.0` release seems to break...something.. in the CI build that I cannot diagnose. It seems to be when the initial build of the article happens and it is claiming `terminal input forbidden` which usually means the latex is messed up. But building locally it is fine.  

```
  Error: An error occurred during the initial build of your TeX file.
  Rule: xml in `showyourwork/workflow/rules/xml.smk`
  Script: `showyourwork/workflow/scripts/xml.py`
  
  Context: This is the initial build step for your article, in which showyourwork
  builds an XML tree of your figure environments to determine the relationship
  between figure scripts and figure files. The `src/ms.tex` file is copied to a
  temporary file called `.showyourwork-xml-ms.tex`, so you might see references to
  that file in the messages below. Note that line numbers may be offset by one
  relative to your original `ms.tex` file.
  
  Detailed message: 
  
  error: terminal input forbidden
```

This is the error message, any thoughts?

**Comment by rodluger** [comment] 2021-12-08 14:13
Can you send me the full raw log on CI, as well as the build artifact?

**Comment by rodluger** [comment] 2021-12-08 14:17
One other thing you can do is delete the `.showyourwork` folder locally to clear the local cache. This might trigger the error you're seeing locally.

**Comment by arm61** [comment] 2021-12-08 14:25
Sent it over! Thanks for the help 🙂
